[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.pylint.messages_control]
max-line-length = 120
disable = [
    "dangerous-default-value",
    "E1120", # no-value-for-parameter, decorators break this
]
