name: PR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python Requirements
        run: make init

      - name: Lint everything
        run: make lint

      - name: Run tests
        run: make test
