name: PR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4

      - name: Install Python Requirements
        run: make init

      - name: Run tests
        run: make test
